MONGODB_HOST: mongodb.krishna.icu
REDIS_HOST: redis.krishna.icu
CATALOGUE_HOST: catalogue.krishna.icu
CART_HOST: cart.krishna.icu
USER_HOST: user.krishna.icu
RABBITMQ_HOST: rabbitmq.krishna.icu
MYSQL_HOST: mysql.krishna.icu
SHIPPING_HOST: shipping.krishna.icu
PAYMENT_HOST: payment.krishna.icu